[project]
name = 'Supply-Chain-Verification-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.iot-integration]
path = 'contracts/iot-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.product-nft]
path = 'contracts/product-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.product-registration]
path = 'contracts/product-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.supply-chain-checkpoints]
path = 'contracts/supply-chain-checkpoints.clar'
clarity_version = 2
epoch = 2.5

[contracts.verification-process]
path = 'contracts/verification-process.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
